alias r="ranger"
alias v="vim"
alias rmu="ranger ~/music"
alias rp="ranger ~/IIS/poland"

# config files
alias cb="vim ~/.bashrc"
alias cba="vim ~/.bash_aliases"
alias cx="vim ~/.Xresources"
alias ci3="vim ~/.config/i3/config"
alias ci3b="vim ~/.i3status.conf"
alias ci3blocks="vim ~/.config/i3blocks/config"
alias cdunst="vim ~/.config/dunst/dunstrc"
alias cv="vim ~/.vimrc"
alias cqb="vim ~/.config/qutebrowser/config.py"
alias cr="vim ~/.config/ranger/rc.conf"
alias crifle="vim ~/.config/ranger/rifle.conf"
alias ccmus="vim ~/.config/cmus/autosave"
alias cg="vim ~/.gitconfig"
alias cnb="vim ~/.newsboat/config"
alias cnbu="vim ~/.newsboat/urls"

alias upgrade="sudo apt-get update && sudo apt-get upgrade"

alias starwars="telnet towel.blinkenlights.nl"
alias nintendos="mpv -vo caca https://www.youtube.com/watch?v=hYNcJj2QDhk 2>/dev/null"
alias adormir="mpv -vo caca ~/videos/Adormir.mp4 && clear 2>/dev/null"
alias adormirloop="mpv --loop-file -vo caca ~/videos/Adormir.mp4 2>/dev/null && clear"
