#!/bin/sh

case "$1" in
	"s")
		width=$(echo "" | dmenu -p "Width of new files?")
		[ "$width" ] || exit 0
		height=$(echo "" | dmenu -p "Height of new files?")
		[ "$height" ] || exit 0
		modifier=""
		[ "$(printf "Yes\nNo" | dmenu -i -p "Maintain aspect ratio?")" = "No" ] && modifier="!"
		while read file
		do
			convert "$file" -resize "$width"x"$height""$modifier" "$width"x"$height""$modifier"_"$file"
		done ;;
	"y")
		text=""
		while read file
		do
			text="$text""$file""\n"
		done
		echo -en "$text" | xsel -ib  &&
		dunstify "$(xsel -ob) copied to clipboard" ;;
	"Y")
		text=""
		while read file
		do
		text="$text""$(readlink -f "$file")""\n"
		done
		echo -en "$text" | xsel -ib &&
		dunstify "$(xsel -ob) copied to clipboard" ;;
	"h")
		dunstify "\
w: Set as wallpaper.                        .
r: Rotate clockwise.                        .
R: Rotate counter-clockwise.                .
f: Flop (horizontally).                     .
f: Flip (vertically).                       .
y: Yank filename to clipboard.              .
Y: Yank file path to clipboard.             .
d: Delete file (with confirmation prompt).  .
n: Rename file.                             .
N: Open in a new instance of sxiv.          .
g: Open in gimp.                            .
s: Create new image with different size.    .
S: Search image online.                     .
c: Copy images to a chosen folder.          .
m: Move images to a chosen folder.          .
h: Show help.                               ." ;;
esac

while read file
do
	case "$1" in
	"w") setBG.sh "$file" ;;
	"r")
		convert -rotate 90 "$file" "$file" &&
		dunstify "$file rotated clockwise" ;;
	"R")
		convert -rotate -90 "$file" "$file" &&
		dunstify "$file rotated counter-clockwise" ;;
	"f")
		convert -flop "$file" "$file" &&
		dunstify "$file flopped" ;;
	"F")
		convert -flip "$file" "$file" &&
		dunstify "$file flipped" ;;
	"d")
		[ "$(printf "No\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && dunstify "$file deleted." ;;
	"n")
		newname="$(dmenu -p "New name of $file?")"
		[ "$newname" ] && newname="$newname"'.'"${file##*.}" && [ "$(printf "No\nYes" | dmenu -i -p "Rename $file to $newname?")" = "Yes" ] && mv "$file" "$newname" && dunstify "$file renamed to $newname." ;;
	"N")
		sxiv -b "$file" & ;;
	"g")
		gimp "$file" & ;;
	"S")
		echo -n "$(readlink -f "$file")" | xsel -ib && dunstify "$(xsel -ob) copied to clipboard"
		$BROWSER "https://tineye.com/" ;;
	"c")
		[ -z "$destdir" ] && destdir="$(selectPath.sh "Copy image(s) to:")"
		[ -z "$destdir" ] && exit
		replace="Yes"
		if [ -e "$destdir""$file" ]; then
			dunstify -i "$destdir""$file" "Old:"
			dunstify -i "$(readlink -f "$file")" "New:"
			replace="$(echo -e "No\nYes" | dmenu -i -p "Replace $file in $destdir?")"
		fi
		[ "$replace" = "Yes" ] && cp "$file" "$destdir" && dunstify -t 2000 -i "$(readlink -f "$file")" "$file copied to $destdir" & ;;
	"m")
		[ -z "$destdir" ] && destdir="$(selectPath.sh "Move image(s) to:")"
		[ -z "$destdir" ] && exit
		replace="Yes"
		if [ -e "$destdir""$file" ]; then
			dunstify -i "$destdir""$file" "Old:"
			dunstify -i "$(readlink -f "$file")" "New:"
			replace="$(echo -e "No\nYes" | dmenu -i -p "Replace $file in $destdir?")"
		fi
		[ "$replace" = "Yes" ] && mv "$file" "$destdir" && dunstify -t 2000 -i "$destdir$file" "$file moved to $destdir" & ;;
	esac
done
